// Code generated by "stringer -type=Lamp"; DO NOT EDIT.

package display

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Off-0]
	_ = x[Red-1]
	_ = x[Green-2]
	_ = x[Amber-3]
}

const _Lamp_name = "OffRedGreenAmber"

var _Lamp_index = [...]uint8{0, 3, 6, 11, 16}

func (i Lamp) String() string {
	if i >= Lamp(len(_Lamp_index)-1) {
		return "Lamp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Lamp_name[_Lamp_index[i]:_Lamp_index[i+1]]
}
